# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name' : 'Thirst Customization',
    'version' : '1.2',
    'summary': 'Thirst Customization',
    'sequence': 100,
    'description': """ Thirst Customization """,
    'category': 'Website',
    'website': 'http://www.strategicdimensions.co.za',
    'depends' : ['base', 'crm', 'point_of_sale', 'base_setup', 'sale', 'purchase', 'hr', 'account', 'project', 'product', 'beverages', 'website_quote', 'partner_credit_limit', 'smsclient', 'website_form_editor', 'website_sale', 'sale_margin'],
    'data': [
#             'security/thirst_security.xml',
            'security/ir.model.access.csv',
            'views/project_view.xml',
            'views/sale_view.xml',
            'views/templates.xml',
            'views/get_a_quote.xml',
            'data/crm_form_data.xml',
            'views/website_form_editor.xml',
            # 'views/cocktail_templates.xml',
            'views/pos_config_view.xml',
            'views/pos_order_view.xml',
            'views/crm_lead_view.xml',
            'views/product_view.xml',
            'views/account_invoice_view.xml',
            'views/hr_view.xml',
            'views/project_staff_view.xml',
            'views/purchase_order_view.xml',
            'views/email_templates.xml',
            'views/website_quote_templates.xml',
            'report/sale_report_template.xml',
            'report/thirst_reports.xml',
            'report/stock_sheet_report.xml',
            'report/invoice_report_template.xml',
            'report/invoice_report_format.xml',
            'report/purchase_order_templates.xml',
            'report/staff_report_templates.xml',
            'report/staff_costing_report_templates.xml',
            ],
    'qweb':['static/src/xml/pos.xml', 'static/src/xml/account_report_backend.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
